# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LU+BXV2/NopDaObmBKuBFBO9AcG4P+MZa3tFpyYP+2hRcZe9ims7xeUEyvJ8U7DGahXLl1DhyH2GgVl9YONG1DRFvH8d1oeIFwtKMjRLUpqMkK51VZZTwFrJhC7tNaW6VXEQwE7KQQk3cgVvniB2L9ia+XPi5GYNb1ncwB9bpIPtWKlvzjTNRe6X655y3LbP1qVX3knY96NI/0PpDYqfQTLXbMBX4909z8Y6zu1jl/QUy0uV/+RtAE64ZLz4r1HkKVbPUX7oIBPO8nFGxffZBCpoaUQklo1/0gWsN7LEEv2LpnddemQMqDTFiL6NJOTi8ukqaazdx1q4QTKOdKcvrEuAvtP6wEnQg/U7ldf51+QbXN2m1GBTr89n6ajBobGCyLS1N9JFo8+GWi3Qj5AxtZF4oszXWy24JIKtP5nvo/rfZ7X3sWodR3lsF5lJ5dlgEouyYAl1fhf1zJOqCKGcVRaFWDD4gygP/kw+utuRCLRpA2MEK/7umE9cP3dyInewMyi+EMx/HJSMcgnytPYwVpfPxAC5rhUdl3Q6sKsgVuv73qWDv+AfPN+YeuwXct6xIuA7bdh3Gnv58zHoLyajsNxeLR9U8YOGdATWYoSAEP6wMJ3XuvVhpqAAaj+8ZE/AI0DoSRryQBfiUZVZX5s050S6wgOlNucj/BefXwEfCK8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml